### ISSUE TITLE
Installation package

### ISSUE THREAD

**Issue by laurentb0204** [VitorLuizC/gulp-html-accents#6]
Hi,

I can not install gulp-html-accents, I have try some methods, but no one works. 
npm install gulp-html-accents
npm install git+https://github.com/VitorLuizC/gulp-html-accents.git

Have you an idea ?

Best regards,

Laurent BROUCK

**Comment by VitorLuizC** [comment]
I can't reproduce it. I'd installed without any trouble

![Screenshot](https://user-images.githubusercontent.com/9027363/33619137-931ef696-d9cb-11e7-85cb-53168488048e.png)

Can you show the error message?

**Comment by laurentb0204** [comment]
Installation looks ok, I have this result:
_npm WARN package.json xxx@1.0.0 No description
npm WARN package.json xxx@1.0.0 No repository field.
npm WARN package.json xxx@1.0.0 No README data
gulp-html-accents@3.1.0 node_modules\gulp-html-accents
├── through2@2.0.3 (xtend@4.0.1, readable-stream@2.3.3)
└── gulp-util@3.0.8 (array-differ@1.0.0, array-uniq@1.0.3, beeper@1.1.1, lodash._reevaluate@3.0.0, lodash._reescape@3.0.
0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, dateformat@2.2.0, has-gulplog@0.1.0, minimist@1.
2.0, fancy-log@1.3.0, vinyl@0.5.3, gulplog@1.0.0, chalk@1.1.3, lodash.template@3.6.2, multipipe@0.1.2)_
 But in "gulpfile.js", when I declare : 
var gulp = require("gulp"),
    replaceHtmlAccents = require('gulp-html-accents');
My gulpFile doesn't work....
(I have made the same operation with gulp-html-entities and when I declare "require('gulp-html-entities')", the file gulFile.js is ok).
Why gulp-html-accents is not recognized ?

Thanks

**Comment by laurentb0204** [comment]
Thanks for your answer, my problem is in gulpfile.js, Below, this is what I see in output window.
	_Failed to run "C:\xxx\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:\xxx\node_modules\gulp-html-accents\index.js:3
const { PluginError } = require('gulp-util');
      ^
SyntaxError: Unexpected token { ... }_

It looks on each "{" character inside function or declaration variable.
Have you an idea of this problem ?

Laurent BROUCK

**Comment by VitorLuizC** [comment]
That's because JavaScript destructuring assignment. You can fix this using Node.js version 6 or higher. But I can also transpile down to ES5 and cover some future related issues.

**Comment by laurentb0204** [comment]
Ok, I'm currently in version 4.4.5 of Node.js, I will install new version, and reinstall and test. Thanks for your answer.

Laurent

**Comment by VitorLuizC** [comment]
I've transpiled it down to ES5 and published under 3.2 version.
